FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY . /usr/share/nginx/html

EXPOSE 10000

CMD ["/bin/sh", "-c", "sed -i 's/listen 80;/listen 10000;/; s/node-api:5000/node-api:10000/g; s/data-backend:8000/data-backend:10000/g; s/ai-service:8001/ai-service:10000/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
