// CiviSight Comprehensive Datasets
// Government Records, Population & Demographics, Facilities, Citizen Ground Reports, and AI Recommendations

export const districtDemographics = [
  { district: "Visakhapatnam", population: 2358000, density: 1840, vulnerabilityIndex: 0.28, facilitiesCount: 412, deficitPockets: ["Pendurthi West", "Gajuwaka Industrial Zone", "Anandapuram North"] },
  { district: "Vijayawada", population: 1475000, density: 3120, vulnerabilityIndex: 0.32, facilitiesCount: 320, deficitPockets: ["Sector 3 Canal Bank", "Ajit Singh Nagar Slums", "Payakapuram"] },
  { district: "Guntur", population: 1028000, density: 2450, vulnerabilityIndex: 0.39, facilitiesCount: 260, deficitPockets: ["Old Market Slum Zone", "Nallapadu Habitation", "Gorantla East"] },
  { district: "Kurnool", population: 985000, density: 1680, vulnerabilityIndex: 0.44, facilitiesCount: 215, deficitPockets: ["Ward 4 Riverfront", "Kallur South", "Joharapuram"] },
  { district: "Tirupati", population: 890000, density: 1950, vulnerabilityIndex: 0.29, facilitiesCount: 195, deficitPockets: ["Outer Ring Habitations", "Renigunta Peri-urban", "Chandragiri Road"] },
];

export const seedFacilities = [
  // Visakhapatnam
  {
    id: "fac-vskp-01",
    name: "Zilla Parishad Primary School (Pendurthi)",
    type: "school",
    district: "Visakhapatnam",
    lat: 17.8284,
    lng: 83.1985,
    officialStatus: "ABANDONED",
    abandonmentScore: 92,
    populationCatchment: 14200,
    establishedYear: 1994,
    lastInspection: "18 months ago",
    conditionNotes: "Zero student enrollment for 3 years following cluster school consolidation. Sturdy RCC building with 6 classrooms and play area, completely overgrown with wild vegetation.",
    citizenReportCount: 6,
    recommendedAction: "REPURPOSE",
    proposedUse: "Primary Health Clinic & Anganwadi Center",
  },
  {
    id: "fac-vskp-02",
    name: "Pendurthi Public Sanitation Block #4",
    type: "toilet",
    district: "Visakhapatnam",
    lat: 17.8251,
    lng: 83.2041,
    officialStatus: "DEFUNCT",
    abandonmentScore: 84,
    populationCatchment: 6500,
    establishedYear: 2018,
    lastInspection: "7 months ago",
    conditionNotes: "Padlocked steel gate, dry overhead tank, broken external tap. Citizen reports state contractor ceased maintenance after contract dispute.",
    citizenReportCount: 9,
    recommendedAction: "REPAIR",
    proposedUse: "Restore Water Line, Unlock Doors & Transfer to Women SHG Caretaker",
  },
  {
    id: "fac-vskp-03",
    name: "MVP Colony RO Drinking Water Plant",
    type: "water",
    district: "Visakhapatnam",
    lat: 17.7428,
    lng: 83.3371,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 12,
    populationCatchment: 12000,
    establishedYear: 2020,
    lastInspection: "15 days ago",
    conditionNotes: "Functional 2000 LPH RO water plant dispensing clean water to 800+ households daily.",
    citizenReportCount: 1,
    recommendedAction: "MAINTAIN",
  },
  {
    id: "fac-vskp-04",
    name: "Gajuwaka Old Municipal Dispensary",
    type: "health",
    district: "Visakhapatnam",
    lat: 17.6942,
    lng: 83.2185,
    officialStatus: "UNDERUTILIZED",
    abandonmentScore: 71,
    populationCatchment: 18500,
    establishedYear: 2003,
    lastInspection: "11 months ago",
    conditionNotes: "Staffed only twice a month. High footfall area with severe doctor shortage; premises mostly dark and utilized as informal dumping ground.",
    citizenReportCount: 5,
    recommendedAction: "REPURPOSE",
    proposedUse: "Urban Telemedicine & Diagnostic Hub",
  },
  {
    id: "fac-vskp-05",
    name: "Madhurawada Community Hall & Skill Yard",
    type: "community",
    district: "Visakhapatnam",
    lat: 17.8182,
    lng: 83.3541,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 18,
    populationCatchment: 16000,
    establishedYear: 2021,
    lastInspection: "1 month ago",
    conditionNotes: "Active multi-purpose hall with regular youth training sessions and community functions.",
    citizenReportCount: 0,
    recommendedAction: "MAINTAIN",
  },

  // Vijayawada
  {
    id: "fac-vja-01",
    name: "Krishna Riverfront Public Toilet Complex",
    type: "toilet",
    district: "Vijayawada",
    lat: 16.5123,
    lng: 80.6214,
    officialStatus: "DEFUNCT",
    abandonmentScore: 88,
    populationCatchment: 11000,
    establishedYear: 2017,
    lastInspection: "8 months ago",
    conditionNotes: "Doors rusted shut with chain lock. Foul smell from exterior leaking pipe. Serves dense pedestrian ghat zone but completely inoperable.",
    citizenReportCount: 14,
    recommendedAction: "REPAIR",
    proposedUse: "Urgent plumbing overhaul, biometric caretaker lock, solar lighting",
  },
  {
    id: "fac-vja-02",
    name: "Sector 3 Municipal Primary School",
    type: "school",
    district: "Vijayawada",
    lat: 16.5298,
    lng: 80.6482,
    officialStatus: "UNDERUTILIZED",
    abandonmentScore: 68,
    populationCatchment: 19000,
    establishedYear: 1989,
    lastInspection: "4 months ago",
    conditionNotes: "Only 18 students enrolled in 12-classroom facility. 8 classrooms locked and collecting dust while nearby ward lacks public library.",
    citizenReportCount: 3,
    recommendedAction: "REPURPOSE",
    proposedUse: "Convert vacant wing into Public Reading Room & Digital Library",
  },
  {
    id: "fac-vja-03",
    name: "Ajit Singh Nagar Water Booster Pumping Station",
    type: "water",
    district: "Vijayawada",
    lat: 16.5412,
    lng: 80.6385,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 22,
    populationCatchment: 24000,
    establishedYear: 2015,
    lastInspection: "2 weeks ago",
    conditionNotes: "Operational pump delivering municipal water to 4 zones on alternating schedules.",
    citizenReportCount: 2,
    recommendedAction: "MAINTAIN",
  },
  {
    id: "fac-vja-04",
    name: "Autonagar Transit Rest House & Depot",
    type: "transport",
    district: "Vijayawada",
    lat: 16.4984,
    lng: 80.6721,
    officialStatus: "ABANDONED",
    abandonmentScore: 89,
    populationCatchment: 8500,
    establishedYear: 2008,
    lastInspection: "2 years ago",
    conditionNotes: "Depot abandoned after bus route reorganization. Structural slab and parking yard intact; heavy overnight anti-social activity reported.",
    citizenReportCount: 8,
    recommendedAction: "REPURPOSE",
    proposedUse: "Electric Vehicle (EV) Public Fast-Charging & Logistics Hub",
  },

  // Guntur
  {
    id: "fac-gtr-01",
    name: "Old Market Complex Public Restrooms",
    type: "toilet",
    district: "Guntur",
    lat: 16.3045,
    lng: 80.4418,
    officialStatus: "DEFUNCT",
    abandonmentScore: 91,
    populationCatchment: 13500,
    establishedYear: 2014,
    lastInspection: "10 months ago",
    conditionNotes: "Severely choked inlet, locked by shopkeepers association due to lack of municipal sweepers.",
    citizenReportCount: 16,
    recommendedAction: "REPAIR",
    proposedUse: "High-pressure sanitization, automated pay-and-use turnstile, graywater recycling",
  },
  {
    id: "fac-gtr-02",
    name: "Gorantla ZP Boys High School (East Wing)",
    type: "school",
    district: "Guntur",
    lat: 16.3289,
    lng: 80.4632,
    officialStatus: "ABANDONED",
    abandonmentScore: 86,
    populationCatchment: 15400,
    establishedYear: 1982,
    lastInspection: "1 year ago",
    conditionNotes: "Entire east wing vacant since 2022. Roof tiles intact, electricity connection present but meter disconnected.",
    citizenReportCount: 4,
    recommendedAction: "REPURPOSE",
    proposedUse: "Vocational & Polytechnic Skill Center for Youth",
  },
  {
    id: "fac-gtr-03",
    name: "Nallapadu JJM Community Solar Water Tap",
    type: "water",
    district: "Guntur",
    lat: 16.2845,
    lng: 80.4087,
    officialStatus: "DEFUNCT",
    abandonmentScore: 78,
    populationCatchment: 5200,
    establishedYear: 2021,
    lastInspection: "5 months ago",
    conditionNotes: "Solar panels covered in thick industrial dust, battery inverter failed in April 2026. Zero water discharge.",
    citizenReportCount: 11,
    recommendedAction: "REPAIR",
    proposedUse: "Replace 1.5 HP inverter and wash panels to restore water security",
  },

  // Kurnool
  {
    id: "fac-knl-01",
    name: "Ward 4 Solar Drinking Water Tank",
    type: "water",
    district: "Kurnool",
    lat: 15.8341,
    lng: 78.0421,
    officialStatus: "DEFUNCT",
    abandonmentScore: 94,
    populationCatchment: 8400,
    establishedYear: 2019,
    lastInspection: "6 months ago",
    conditionNotes: "Dry taps for 4 months. Burnt submersible motor never replaced. Residents forced to pay private water tankers ₹800 per delivery.",
    citizenReportCount: 19,
    recommendedAction: "REPAIR",
    proposedUse: "Emergency motor replacement and distribution valve calibration",
  },
  {
    id: "fac-knl-02",
    name: "Old Tungabhadra Canal Inspection Bungalow",
    type: "government",
    district: "Kurnool",
    lat: 15.8412,
    lng: 78.0563,
    officialStatus: "ABANDONED",
    abandonmentScore: 90,
    populationCatchment: 9200,
    establishedYear: 1978,
    lastInspection: "3 years ago",
    conditionNotes: "Colonial-era masonry building on 1.2 acre public land parcel. Roof sound, grounds unmaintained.",
    citizenReportCount: 3,
    recommendedAction: "REPURPOSE",
    proposedUse: "Public Herbal Park, Eco-Tourism Center & Urban Wellness Hub",
  },
  {
    id: "fac-knl-03",
    name: "Kallur Community Health Sub-Center",
    type: "health",
    district: "Kurnool",
    lat: 15.8124,
    lng: 78.0289,
    officialStatus: "UNDERUTILIZED",
    abandonmentScore: 65,
    populationCatchment: 14000,
    establishedYear: 2011,
    lastInspection: "3 months ago",
    conditionNotes: "Sub-center operates only 2 half-days per week. Maternity room locked; ceiling fan dislodged.",
    citizenReportCount: 7,
    recommendedAction: "REPAIR",
    proposedUse: "Immediate structural refurbishment & full-time nurse staffing",
  },

  // Tirupati
  {
    id: "fac-tpt-01",
    name: "Renigunta Road Municipal Toilet Facility",
    type: "toilet",
    district: "Tirupati",
    lat: 13.6394,
    lng: 79.4421,
    officialStatus: "DEFUNCT",
    abandonmentScore: 82,
    populationCatchment: 7800,
    establishedYear: 2016,
    lastInspection: "9 months ago",
    conditionNotes: "Rusted gate chain locked. Heavy transit pilgrim traffic forced to open defecate nearby.",
    citizenReportCount: 13,
    recommendedAction: "REPAIR",
    proposedUse: "Urgent unlock, 24x7 municipal caretaker deployment with automated water sensors",
  },
  {
    id: "fac-tpt-02",
    name: "Chandragiri Road Old Agro-Storage Godown",
    type: "community",
    district: "Tirupati",
    lat: 13.6212,
    lng: 79.3912,
    officialStatus: "ABANDONED",
    abandonmentScore: 87,
    populationCatchment: 11200,
    establishedYear: 1996,
    lastInspection: "2 years ago",
    conditionNotes: "Disused warehouse with large open steel truss space. Inactive since commercial godown shifted to outskirts.",
    citizenReportCount: 2,
    recommendedAction: "REPURPOSE",
    proposedUse: "Farmers' Direct Cold-Storage & Organic Micro-Processing Hub",
  },
  {
    id: "fac-tpt-03",
    name: "Alipiri Foothills Public Health Post",
    type: "health",
    district: "Tirupati",
    lat: 13.6621,
    lng: 79.4085,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 10,
    populationCatchment: 28000,
    establishedYear: 2022,
    lastInspection: "1 week ago",
    conditionNotes: "High performance triage and emergency care facility serving local residents and pilgrims.",
    citizenReportCount: 0,
    recommendedAction: "MAINTAIN",
  },
];

export const seedCivicReports = [
  {
    id: "civ-rep-101",
    facilityId: "fac-knl-01",
    facilityName: "Ward 4 Solar Drinking Water Tank",
    issueType: "DEFUNCT_WATER",
    issueTitle: "This water facility hasn't worked for months",
    district: "Kurnool",
    lat: 15.8341,
    lng: 78.0421,
    description: "This solar drinking water pump broke down 4 months ago. The solar panel wires are snapped and the storage tank is bone dry. Over 500 families in our slum have no tap water.",
    conditionSeverity: "CRITICAL",
    reportedBy: "K. Venkatesh (Resident)",
    submittedAt: "2026-09-14T11:20:00Z",
    status: "CONFIRMED_ISSUE",
    aiTags: ["DRY_TAPS", "SNAPPED_WIRING", "SEVERELY_DEFUNCT", "HIGH_POPULATION_IMPACT"],
    aiConfidence: 94,
    mediaUrl: "",
  },
  {
    id: "civ-rep-102",
    facilityId: "fac-vskp-01",
    facilityName: "Zilla Parishad Primary School (Pendurthi)",
    issueType: "ABANDONED_SCHOOL",
    issueTitle: "This school is abandoned",
    district: "Visakhapatnam",
    lat: 17.8284,
    lng: 83.1985,
    description: "The primary school building has been abandoned for more than 3 years. Weeds and bushes are overgrowing the verandas and classroom windows are smashed. It is a waste of a solid government building.",
    conditionSeverity: "HIGH",
    reportedBy: "S. Anuradha (Local Ward Member)",
    submittedAt: "2026-09-12T16:40:00Z",
    status: "EVALUATION_PENDING",
    aiTags: ["VEGETATION_OVERGROWTH", "ZERO_ENROLLMENT", "STRUCTURALLY_SOUND", "REPURPOSE_CANDIDATE"],
    aiConfidence: 91,
    mediaUrl: "",
  },
  {
    id: "civ-rep-103",
    facilityId: "fac-vja-01",
    facilityName: "Krishna Riverfront Public Toilet Complex",
    issueType: "LOCKED_TOILET",
    issueTitle: "This toilet is locked",
    district: "Vijayawada",
    lat: 16.5123,
    lng: 80.6214,
    description: "Heavy iron chain and rusted padlock have been on the gate since January. People visiting the river ghat and daily wage workers have no sanitation facility. Please unlock and staff this facility.",
    conditionSeverity: "CRITICAL",
    reportedBy: "M. Ramesh (Auto Union)",
    submittedAt: "2026-09-15T08:10:00Z",
    status: "INTERVENTION_RECOMMENDED",
    aiTags: ["PADLOCKED_GATE", "PUBLIC_SANITATION_DENIED", "RUST_CORROSION"],
    aiConfidence: 96,
    mediaUrl: "",
  },
  {
    id: "civ-rep-104",
    facilityId: "fac-gtr-01",
    facilityName: "Old Market Complex Public Restrooms",
    issueType: "LOCKED_TOILET",
    issueTitle: "This facility hasn't been functioning",
    district: "Guntur",
    lat: 16.3045,
    lng: 80.4418,
    description: "The restrooms are totally locked up and sewage backflow has created an unbearable stench around vegetable stalls. Shopkeepers have protested multiple times.",
    conditionSeverity: "HIGH",
    reportedBy: "G. Lakshmi (Market Vendor)",
    submittedAt: "2026-09-11T14:35:00Z",
    status: "CONFIRMED_ISSUE",
    aiTags: ["CLOGGED_SEWAGE", "LOCKED_COMMERCIAL_ZONE", "HEALTH_HAZARD"],
    aiConfidence: 89,
    mediaUrl: "",
  },
  {
    id: "civ-rep-105",
    facilityId: "fac-tpt-01",
    facilityName: "Renigunta Road Municipal Toilet Facility",
    issueType: "LOCKED_TOILET",
    issueTitle: "This toilet is locked and abandoned",
    district: "Tirupati",
    lat: 13.6394,
    lng: 79.4421,
    description: "Built under public funds in 2016, but locked for the past 9 months with weeds blocking the entryway. Tourists and pilgrims are severely inconvenienced.",
    conditionSeverity: "HIGH",
    reportedBy: "T. Srinivasan (Shopkeeper)",
    submittedAt: "2026-09-13T09:50:00Z",
    status: "EVALUATION_PENDING",
    aiTags: ["LOCKED_STRUCTURE", "TRANSIT_DEFICIT", "MAINTENANCE_LAPSE"],
    aiConfidence: 92,
    mediaUrl: "",
  },
  {
    id: "civ-rep-106",
    facilityId: "fac-gtr-03",
    facilityName: "Nallapadu JJM Community Solar Water Tap",
    issueType: "DEFUNCT_WATER",
    issueTitle: "This water facility hasn't worked for months",
    district: "Guntur",
    lat: 16.2845,
    lng: 80.4087,
    description: "Solar inverter failed during peak summer and nobody came to fix it. We are carrying water pots from 2 kilometers away on foot.",
    conditionSeverity: "HIGH",
    reportedBy: "B. Ratnam (Panchayat Member)",
    submittedAt: "2026-09-10T17:05:00Z",
    status: "INTERVENTION_RECOMMENDED",
    aiTags: ["SOLAR_FAILURE", "WATER_DEFICIT_ZONE", "COMMUNITY_DISTRESS"],
    aiConfidence: 95,
    mediaUrl: "",
  },
];

export const seedRecommendations = [
  // REPAIR RECOMMENDATIONS
  {
    id: "rec-rep-01",
    type: "REPAIR",
    urgency: "CRITICAL",
    priorityScore: 96,
    targetFacilityId: "fac-knl-01",
    targetFacilityName: "Ward 4 Solar Drinking Water Tank",
    district: "Kurnool",
    affectedPopulation: 8400,
    estimatedCost: "₹2.4 Lakhs",
    timelineDays: 7,
    roiScore: 9.8,
    rationale: "Highest civic distress report concentration in Kurnool. Submersible motor failure cut off 8,400 vulnerable residents from daily drinking water. Immediate ₹2.4L expenditure resolves extreme water scarcity.",
    actionItems: [
      "Procure & install 2.0 HP heavy-duty submersible motor",
      "Rewire solar array with anti-theft conduits",
      "Sanitize distribution tank and calibrate communal taps",
      "Deploy water quality sensors with daily telemetry",
    ],
    status: "APPROVED_FOR_TENDER",
  },
  {
    id: "rec-rep-02",
    type: "REPAIR",
    urgency: "HIGH",
    priorityScore: 91,
    targetFacilityId: "fac-vja-01",
    targetFacilityName: "Krishna Riverfront Public Toilet Complex",
    district: "Vijayawada",
    affectedPopulation: 11000,
    estimatedCost: "₹1.8 Lakhs",
    timelineDays: 10,
    roiScore: 9.4,
    rationale: "Dense pedestrian transit corridor along river ghat currently plagued by open defecation because facility was locked over minor plumbing leaks.",
    actionItems: [
      "Clear exterior sewage block and replace leaking sanitary pipe",
      "Remove padlock and replace doors with vandalism-resistant composites",
      "Transfer daily operations to local Women SHG under municipal incentive model",
    ],
    status: "PLANNED",
  },
  {
    id: "rec-rep-03",
    type: "REPAIR",
    urgency: "HIGH",
    priorityScore: 88,
    targetFacilityId: "fac-gtr-01",
    targetFacilityName: "Old Market Complex Public Restrooms",
    district: "Guntur",
    affectedPopulation: 13500,
    estimatedCost: "₹3.2 Lakhs",
    timelineDays: 14,
    roiScore: 9.1,
    rationale: "Major urban commercial hub. 16 citizen reports received. High disease outbreak hazard if sewage stagnation continues near fresh food market.",
    actionItems: [
      "Deep jetting of subterranean sewer connection",
      "Installation of automated water-saving sensor flushes",
      "Sanitary inspection sign-off and public grievance QR code installation",
    ],
    status: "IN_REVIEW",
  },
  {
    id: "rec-rep-04",
    type: "REPAIR",
    urgency: "MEDIUM",
    priorityScore: 82,
    targetFacilityId: "fac-gtr-03",
    targetFacilityName: "Nallapadu JJM Community Solar Water Tap",
    district: "Guntur",
    affectedPopulation: 5200,
    estimatedCost: "₹95,000",
    timelineDays: 5,
    roiScore: 8.9,
    rationale: "Low-cost high-impact intervention. Quick inverter swap restores tap water to 5,200 rural residents.",
    actionItems: [
      "Replace burnt solar inverter with lightning surge arrestor",
      "Pressure-wash solar panels and replace damaged battery bank",
    ],
    status: "PLANNED",
  },

  // REPURPOSE RECOMMENDATIONS
  {
    id: "rec-pur-01",
    type: "REPURPOSE",
    urgency: "HIGH",
    priorityScore: 93,
    targetFacilityId: "fac-vskp-01",
    targetFacilityName: "Zilla Parishad Primary School (Pendurthi)",
    district: "Visakhapatnam",
    affectedPopulation: 14200,
    estimatedCost: "₹8.5 Lakhs",
    timelineDays: 45,
    roiScore: 9.6,
    rationale: "Structurally sound 6-room school building abandoned for 3 years due to cluster school amalgamation. Nearby ward lacks any primary healthcare sub-center, forcing mothers to travel 7km for immunizations.",
    proposedUse: "Primary Health Sub-Center & Child Anganwadi Nutrition Hub",
    actionItems: [
      "Clear wild vegetation and repair perimeter compound wall",
      "Partition 4 classrooms into doctor consultation, immunization, and pharmacy rooms",
      "Convert 2 classrooms into mother-child Anganwadi center with indoor learning toys",
      "Deploy rooftop 5kW solar unit and install cold-chain vaccine refrigerator",
    ],
    status: "FEASIBILITY_APPROVED",
  },
  {
    id: "rec-pur-02",
    type: "REPURPOSE",
    urgency: "HIGH",
    priorityScore: 89,
    targetFacilityId: "fac-vja-04",
    targetFacilityName: "Autonagar Transit Rest House & Depot",
    district: "Vijayawada",
    affectedPopulation: 8500,
    estimatedCost: "₹14.0 Lakhs",
    timelineDays: 60,
    roiScore: 9.2,
    rationale: "Vacant bus depot site creating an anti-social hotspot in an industrial area. Heavy demand for EV commercial 3-wheeler charging and last-mile delivery parking.",
    proposedUse: "Green EV Commercial Charging & Logistics Micro-Depot",
    actionItems: [
      "Erect 60kW DC fast charging stations for municipal & commercial electric three-wheelers",
      "Refurbish rest house into driver sanitarium, resting lounge, and cafeteria",
      "Generate municipal non-fare revenue through charging tariff sharing",
    ],
    status: "PLANNED",
  },
  {
    id: "rec-pur-03",
    type: "REPURPOSE",
    urgency: "MEDIUM",
    priorityScore: 85,
    targetFacilityId: "fac-tpt-02",
    targetFacilityName: "Chandragiri Road Old Agro-Storage Godown",
    district: "Tirupati",
    affectedPopulation: 11200,
    estimatedCost: "₹6.8 Lakhs",
    timelineDays: 30,
    roiScore: 8.7,
    rationale: "Large vacant steel-truss warehouse on highway. Vegetable and mango growers currently lose 22% post-harvest due to lack of local pre-cooling facilities.",
    proposedUse: "Farmer Producer Org (FPO) Solar Cold Storage & Grading Facility",
    actionItems: [
      "Install 15 MT solar-assisted walk-in cold room module",
      "Setup digital weighing and electronic mandi bidding kiosks",
      "Lease operation to registered local Farmer Producer Organization",
    ],
    status: "IN_REVIEW",
  },
  {
    id: "rec-pur-04",
    type: "REPURPOSE",
    urgency: "MEDIUM",
    priorityScore: 81,
    targetFacilityId: "fac-gtr-02",
    targetFacilityName: "Gorantla ZP Boys High School (East Wing)",
    district: "Guntur",
    affectedPopulation: 15400,
    estimatedCost: "₹5.5 Lakhs",
    timelineDays: 35,
    roiScore: 8.5,
    rationale: "Unused school wing structurally sound. Ward has high youth unemployment and lacks technical training facilities.",
    proposedUse: "Youth Digital IT & Robotic Welding Skill Center",
    actionItems: [
      "Fit out 20-workstation computer lab with high-speed fiber",
      "Install certified electrical and tooling vocational workbenches",
      "Partner with National Skill Development Corporation (NSDC)",
    ],
    status: "PLANNED",
  },

  // NEWLY DEVELOP RECOMMENDATIONS
  {
    id: "rec-dev-01",
    type: "NEWLY_DEVELOP",
    urgency: "CRITICAL",
    priorityScore: 97,
    targetFacilityName: "Guntur West Slum Catchment - Sanitation Hub",
    district: "Guntur",
    affectedPopulation: 13800,
    estimatedCost: "₹18.0 Lakhs",
    timelineDays: 90,
    roiScore: 9.9,
    rationale: "Severe civic deficit: Geospatial buffer analysis confirms 13,800 residents have ZERO functional public toilets within 1.8km radius. 34 ground complaints of open defecation hazards.",
    proposedUse: "New Construction: 12-Seat Smart Eco-Sanitation & Bathing Complex",
    actionItems: [
      "Acquire 350 sq.yd available municipal road-end parcel",
      "Construct prefabricated 12-seat dual-gender toilet and bath cubicles with solar power",
      "Install bio-digester tank preventing ground water contamination",
      "Integrate automated coin/UPI pay-and-use mechanism with female attendant post",
    ],
    status: "PROPOSAL_READY",
  },
  {
    id: "rec-dev-02",
    type: "NEWLY_DEVELOP",
    urgency: "HIGH",
    priorityScore: 92,
    targetFacilityId: null,
    targetFacilityName: "Tirupati Outer Ring Habitations Water ATM",
    district: "Tirupati",
    affectedPopulation: 7500,
    estimatedCost: "₹12.5 Lakhs",
    timelineDays: 45,
    roiScore: 9.3,
    rationale: "Groundwater in outer ring colony contains total dissolved solids (TDS) exceeding 1800 ppm. No piped JJM tap infrastructure reaches this newly settled perimeter.",
    proposedUse: "New Construction: 5000 LPH Deep-Bore Solar RO Purified Water Kiosk",
    actionItems: [
      "Drill 450 ft exploratory borewell with geological clearance",
      "Erect 5000 LPH dual-stage RO purification unit with mineral dosing",
      "Dispense 20-liter cans at nominal ₹5 subsidized rate using RFID smart cards",
    ],
    status: "PLANNED",
  },
  {
    id: "rec-dev-03",
    type: "NEWLY_DEVELOP",
    urgency: "HIGH",
    priorityScore: 89,
    targetFacilityId: null,
    targetFacilityName: "Visakhapatnam Anandapuram North Healthcare Sub-Center",
    district: "Visakhapatnam",
    affectedPopulation: 22000,
    estimatedCost: "₹48.0 Lakhs",
    timelineDays: 120,
    roiScore: 9.0,
    rationale: "Rapid peri-urban growth area. Nearest primary health clinic is 6.8km away across an express bypass, creating lethal delays during obstetric emergencies.",
    proposedUse: "New Construction: Urban Primary Health Center (UPHC)",
    actionItems: [
      "Sanction DPR under National Urban Health Mission (NUHM)",
      "Construct 24x7 4-bed stabilization and delivery unit",
      "Staff with 2 medical officers, 4 staff nurses, and lab technician",
    ],
    status: "PROPOSAL_READY",
  },
];

export const seedResolutionPairs = [
  {
    id: "res-01",
    facilityName: "Tirupati Renigunta Sanitation Block #2",
    district: "Tirupati",
    issueReported: "Padlocked steel gate and broken water pipe",
    reportedDate: "2026-08-10",
    resolvedDate: "2026-09-12",
    reportedBy: "S. Murthy",
    resolvedBy: "Assistant Engineer V. Prasad",
    aiVerificationScore: 95,
    status: "VERIFIED_RESOLVED",
    aiInspectionReport: "AI visual inspection confirms padlock has been removed, fresh paint applied, water pipe connected, and entrance is unobstructed for public use.",
  },
  {
    id: "res-02",
    facilityName: "Kurnool Kallur Sub-center Pothole & Entrance Repair",
    district: "Kurnool",
    issueReported: "Deep crater in front of clinic entrance preventing ambulance access",
    reportedDate: "2026-08-20",
    resolvedDate: "2026-09-14",
    reportedBy: "Dr. K. Swamy",
    resolvedBy: "Junior Engineer M. Naik",
    aiVerificationScore: 92,
    status: "VERIFIED_RESOLVED",
    aiInspectionReport: "Bitumen surface fully compacted. No standing water detected. Level gradient allows clear wheelchair and stretcher transit.",
  },
  {
    id: "res-03",
    facilityName: "Vijayawada Sector 3 Water Tap Leakage",
    district: "Vijayawada",
    issueReported: "Severed control valve causing continuous potable water wastage",
    reportedDate: "2026-09-01",
    resolvedDate: "2026-09-15",
    reportedBy: "N. Bhavani",
    resolvedBy: "Water Works Inspector R. Raju",
    aiVerificationScore: 98,
    status: "VERIFIED_RESOLVED",
    aiInspectionReport: "Zero moisture leakage detected around joint. High-grade brass shutoff installed with tamper-proof seal.",
  },
];
