// CivicSight Pan-India National Infrastructure Intelligence Datasets
// Public Assets, Population Demographics, Ground Reports & AI Recommendations across Indian States

export const districtDemographics = [
  { district: "Central Delhi", state: "Delhi", population: 2150000, density: 9240, vulnerabilityIndex: 0.38, facilitiesCount: 380, deficitPockets: ["Seelampur Slums", "Narela Sub-city Outer", "Yamuna Floodplain"] },
  { district: "Mumbai Suburban", state: "Maharashtra", population: 9356000, density: 20980, vulnerabilityIndex: 0.42, facilitiesCount: 620, deficitPockets: ["Dharavi Sector 5", "Mankhurd Transit Camps", "Kurla West Lowline"] },
  { district: "Bengaluru Urban", state: "Karnataka", population: 8443000, density: 4380, vulnerabilityIndex: 0.31, facilitiesCount: 510, deficitPockets: ["Peenya Outer Industrial Slums", "K.R. Puram Transit Cluster", "Ejipura Slum Pockets"] },
  { district: "Chennai", state: "Tamil Nadu", population: 7088000, density: 17100, vulnerabilityIndex: 0.34, facilitiesCount: 440, deficitPockets: ["Vyasarpadi North", "Otteri Canal Habitations", "Ennore Coastal Belt"] },
  { district: "Hyderabad", state: "Telangana", population: 6809000, density: 18480, vulnerabilityIndex: 0.33, facilitiesCount: 490, deficitPockets: ["Old City Charminar South", "Amberpet Canal Edge", "Musi Riverfront Slums"] },
  { district: "Varanasi", state: "Uttar Pradesh", population: 1425000, density: 3100, vulnerabilityIndex: 0.46, facilitiesCount: 310, deficitPockets: ["Adampur Weavers Cluster", "Shivpur Habitations", "Ramnagar Riverbank"] },
  { district: "Kolkata", state: "West Bengal", population: 4496000, density: 24300, vulnerabilityIndex: 0.39, facilitiesCount: 470, deficitPockets: ["Topsia Canal Belt", "Howrah Foreshore", "Metiabruz Riverside"] },
  { district: "Ahmedabad", state: "Gujarat", population: 5570000, density: 11800, vulnerabilityIndex: 0.32, facilitiesCount: 430, deficitPockets: ["Asarwa Closed Mills Belt", "Vatva Industrial Slums", "Danilimda South"] },
  { district: "Jaipur", state: "Rajasthan", population: 3046000, density: 6300, vulnerabilityIndex: 0.35, facilitiesCount: 360, deficitPockets: ["Sanganer Outer", "Jhotwara Slum Pockets", "Transport Nagar East"] },
  { district: "Visakhapatnam", state: "Andhra Pradesh", population: 2358000, density: 1840, vulnerabilityIndex: 0.28, facilitiesCount: 412, deficitPockets: ["Pendurthi West", "Gajuwaka Industrial Zone", "Anandapuram North"] },
  { district: "Vijayawada", state: "Andhra Pradesh", population: 1475000, density: 3120, vulnerabilityIndex: 0.32, facilitiesCount: 320, deficitPockets: ["Sector 3 Canal Bank", "Ajit Singh Nagar Slums", "Payakapuram"] },
  { district: "Guntur", state: "Andhra Pradesh", population: 1028000, density: 2450, vulnerabilityIndex: 0.39, facilitiesCount: 260, deficitPockets: ["Old Market Slum Zone", "Nallapadu Habitation", "Gorantla East"] },
  { district: "Kurnool", state: "Andhra Pradesh", population: 985000, density: 1680, vulnerabilityIndex: 0.44, facilitiesCount: 215, deficitPockets: ["Ward 4 Riverfront", "Kallur South", "Joharapuram"] },
  { district: "Tirupati", state: "Andhra Pradesh", population: 890000, density: 1950, vulnerabilityIndex: 0.29, facilitiesCount: 195, deficitPockets: ["Outer Ring Habitations", "Renigunta Peri-urban", "Chandragiri Road"] }
];

export const seedFacilities = [
  // ─── 1. DELHI NCR ──────────────────────────────────────────────────────────
  {
    id: "fac-del-01",
    name: "MCD Primary Model School (Narela)",
    type: "school",
    district: "Central Delhi",
    state: "Delhi",
    lat: 28.8524,
    lng: 77.0931,
    officialStatus: "ABANDONED",
    abandonmentScore: 94,
    populationCatchment: 24000,
    establishedYear: 1998,
    lastInspection: "22 months ago",
    conditionNotes: "Closed 3 years ago following consolidation with Sarvodaya Vidyalaya. Sturdy 2-story building with 10 vacant classrooms, overgrown courtyard, and rusted gates.",
    citizenReportCount: 12,
    recommendedAction: "REPURPOSE",
    proposedUse: "Maternal & Child Health Care Center & Creche",
  },
  {
    id: "fac-del-02",
    name: "DDA Community Sanitation Complex (Rohini Sector 22)",
    type: "toilet",
    district: "Central Delhi",
    state: "Delhi",
    lat: 28.7182,
    lng: 77.0673,
    officialStatus: "DEFUNCT",
    abandonmentScore: 86,
    populationCatchment: 11000,
    establishedYear: 2017,
    lastInspection: "8 months ago",
    conditionNotes: "Heavy iron chain on main entrance. Citizen reports water motor burned out 8 months ago with zero repairs, forcing open defecation in adjacent vacant plots.",
    citizenReportCount: 15,
    recommendedAction: "REPAIR",
    proposedUse: "Restore Submersible Pump, Install Smart Sensors & Hand Over to Caretaker",
  },
  {
    id: "fac-del-03",
    name: "Delhi Jal Board RO Clean Water ATM (Dwarka Sector 14)",
    type: "water",
    district: "Central Delhi",
    state: "Delhi",
    lat: 28.5921,
    lng: 77.0378,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 8,
    populationCatchment: 18000,
    establishedYear: 2021,
    lastInspection: "12 days ago",
    conditionNotes: "Active automated dispensing kiosk serving 1200+ commuters and residents daily with nominal tariff.",
    citizenReportCount: 1,
    recommendedAction: "MAINTAIN",
  },
  {
    id: "fac-del-04",
    name: "Seelampur Municipal Health Post & Dispensary",
    type: "health",
    district: "Central Delhi",
    state: "Delhi",
    lat: 28.6644,
    lng: 77.2678,
    officialStatus: "UNDERUTILIZED",
    abandonmentScore: 78,
    populationCatchment: 32000,
    establishedYear: 2005,
    lastInspection: "9 months ago",
    conditionNotes: "High density slum catchment. Open only 2 hours on alternate mornings. Medicine dispensary counter locked; premises used for temporary garbage parking.",
    citizenReportCount: 8,
    recommendedAction: "REPURPOSE",
    proposedUse: "24x7 Urban Telemedicine Clinic & Diagnostic Lab",
  },

  // ─── 2. MAHARASHTRA (MUMBAI & PUNE) ─────────────────────────────────────────
  {
    id: "fac-mum-01",
    name: "BMC Municipal Primary School (Kurla West)",
    type: "school",
    district: "Mumbai Suburban",
    state: "Maharashtra",
    lat: 19.0688,
    lng: 72.8797,
    officialStatus: "ABANDONED",
    abandonmentScore: 91,
    populationCatchment: 36000,
    establishedYear: 1989,
    lastInspection: "14 months ago",
    conditionNotes: "School operations ceased during post-COVID student migration. Structurally sound 3-floor building in prime commercial pocket lying idle.",
    citizenReportCount: 11,
    recommendedAction: "REPURPOSE",
    proposedUse: "Dharavi-Kurla Youth Skill Hub & Digital Learning Center",
  },
  {
    id: "fac-mum-02",
    name: "Mankhurd Transit Camp Sanitation Block #12",
    type: "toilet",
    district: "Mumbai Suburban",
    state: "Maharashtra",
    lat: 19.0522,
    lng: 72.9328,
    officialStatus: "DEFUNCT",
    abandonmentScore: 89,
    populationCatchment: 18500,
    establishedYear: 2016,
    lastInspection: "6 months ago",
    conditionNotes: "Sewer line blockage caused complete shutdown. Doors broken, dry taps, extreme sanitation hazard affecting over 3500 families.",
    citizenReportCount: 19,
    recommendedAction: "REPAIR",
    proposedUse: "Drainage Overhaul, Solar Rooftop Lighting & Bio-digester Installation",
  },
  {
    id: "fac-mum-03",
    name: "Andheri Station Clean Water Kiosk",
    type: "water",
    district: "Mumbai Suburban",
    state: "Maharashtra",
    lat: 19.1197,
    lng: 72.8464,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 11,
    populationCatchment: 45000,
    establishedYear: 2022,
    lastInspection: "5 days ago",
    conditionNotes: "High-capacity multi-chilled dispensing kiosk serving rail transit commuters flawlessly.",
    citizenReportCount: 2,
    recommendedAction: "MAINTAIN",
  },
  {
    id: "fac-pune-01",
    name: "Pimpri-Chinchwad Urban Health Post",
    type: "health",
    district: "Mumbai Suburban",
    state: "Maharashtra",
    lat: 18.6279,
    lng: 73.8131,
    officialStatus: "UNDERUTILIZED",
    abandonmentScore: 72,
    populationCatchment: 28000,
    establishedYear: 2011,
    lastInspection: "10 months ago",
    conditionNotes: "Specialist doctors absent. Facility under-equipped with defunct diagnostic apparatus while industrial workers travel 14km to civil hospital.",
    citizenReportCount: 7,
    recommendedAction: "REPURPOSE",
    proposedUse: "Industrial Workers Occupational Health & Trauma Sub-Center",
  },

  // ─── 3. KARNATAKA (BENGALURU) ──────────────────────────────────────────────
  {
    id: "fac-blr-01",
    name: "BBMP Primary School (Peenya 2nd Stage)",
    type: "school",
    district: "Bengaluru Urban",
    state: "Karnataka",
    lat: 13.0329,
    lng: 77.5142,
    officialStatus: "ABANDONED",
    abandonmentScore: 88,
    populationCatchment: 21000,
    establishedYear: 1996,
    lastInspection: "16 months ago",
    conditionNotes: "Building closed since 2023. Premises in industrial belt currently being encroached for unauthorized scrap vehicle parking.",
    citizenReportCount: 9,
    recommendedAction: "REPURPOSE",
    proposedUse: "Garment Workers Creche & Women Skill Training Incubator",
  },
  {
    id: "fac-blr-02",
    name: "Shivajinagar Bus Terminal Public E-Toilet",
    type: "toilet",
    district: "Bengaluru Urban",
    state: "Karnataka",
    lat: 12.9857,
    lng: 77.6057,
    officialStatus: "DEFUNCT",
    abandonmentScore: 85,
    populationCatchment: 28000,
    establishedYear: 2018,
    lastInspection: "5 months ago",
    conditionNotes: "Automated payment gate permanently disabled. Sensor valves stripped, zero running water, dark and locked for 5 consecutive months.",
    citizenReportCount: 14,
    recommendedAction: "REPAIR",
    proposedUse: "Convert to Hybrid Attendant Model with Fixed Sensor Overhaul",
  },
  {
    id: "fac-blr-03",
    name: "Cauvery Drinking Water Point (Kengeri Satellite Town)",
    type: "water",
    district: "Bengaluru Urban",
    state: "Karnataka",
    lat: 12.9177,
    lng: 77.4837,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 10,
    populationCatchment: 14000,
    establishedYear: 2021,
    lastInspection: "18 days ago",
    conditionNotes: "Reliable 24x7 treated municipal water kiosk dispensing 15,000 liters daily.",
    citizenReportCount: 1,
    recommendedAction: "MAINTAIN",
  },
  {
    id: "fac-blr-04",
    name: "Peenya Industrial Labor Health Center",
    type: "health",
    district: "Bengaluru Urban",
    state: "Karnataka",
    lat: 13.0285,
    lng: 77.5218,
    officialStatus: "UNDERUTILIZED",
    abandonmentScore: 74,
    populationCatchment: 35000,
    establishedYear: 2008,
    lastInspection: "7 months ago",
    conditionNotes: "Only 1 nurse on duty twice a week. Essential medicines depleted for over 6 months; night emergency wing shuttered.",
    citizenReportCount: 6,
    recommendedAction: "REPURPOSE",
    proposedUse: "24x7 Industrial Emergency First-Response & Tele-Consult Center",
  },

  // ─── 4. TAMIL NADU (CHENNAI) ────────────────────────────────────────────────
  {
    id: "fac-che-01",
    name: "Greater Chennai Corporation Middle School (T. Nagar)",
    type: "school",
    district: "Chennai",
    state: "Tamil Nadu",
    lat: 13.0418,
    lng: 80.2341,
    officialStatus: "UNDERUTILIZED",
    abandonmentScore: 65,
    populationCatchment: 19000,
    establishedYear: 1982,
    lastInspection: "4 months ago",
    conditionNotes: "Ground floor active with 35 students; upper 2 floors completely abandoned, unlit, with broken louvers and water seepage.",
    citizenReportCount: 4,
    recommendedAction: "REPURPOSE",
    proposedUse: "Upper Floors: Youth Digital Library & STEM Innovation Center",
  },
  {
    id: "fac-che-02",
    name: "Vyasarpadi Slum Cluster Sanitation Facility",
    type: "toilet",
    district: "Chennai",
    state: "Tamil Nadu",
    lat: 13.1118,
    lng: 80.2541,
    officialStatus: "DEFUNCT",
    abandonmentScore: 90,
    populationCatchment: 14500,
    establishedYear: 2017,
    lastInspection: "8 months ago",
    conditionNotes: "Underground drainage collapsed during northeast monsoon. Tap infrastructure vanished, padlocked and surrounded by stagnant blackwater.",
    citizenReportCount: 16,
    recommendedAction: "REPAIR",
    proposedUse: "Elevated Drainage Replacement, Fresh Borewell & Handover to Sanitation SHG",
  },
  {
    id: "fac-che-03",
    name: "Metro Water Kiosk (Koyambedu Wholesale Market)",
    type: "water",
    district: "Chennai",
    state: "Tamil Nadu",
    lat: 13.0694,
    lng: 80.1948,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 9,
    populationCatchment: 38000,
    establishedYear: 2019,
    lastInspection: "3 days ago",
    conditionNotes: "Massive footfall utility dispensing clean potable water to vegetable porters, truckers, and vendors without interruption.",
    citizenReportCount: 0,
    recommendedAction: "MAINTAIN",
  },

  // ─── 5. TELANGANA (HYDERABAD) ───────────────────────────────────────────────
  {
    id: "fac-hyd-01",
    name: "GHMC Old School & Community Center (Amberpet)",
    type: "school",
    district: "Hyderabad",
    state: "Telangana",
    lat: 17.3912,
    lng: 78.5173,
    officialStatus: "ABANDONED",
    abandonmentScore: 87,
    populationCatchment: 22000,
    establishedYear: 1991,
    lastInspection: "15 months ago",
    conditionNotes: "Unused municipal building with reinforced columns and spacious halls. Backyard accumulating illegal construction debris.",
    citizenReportCount: 8,
    recommendedAction: "REPURPOSE",
    proposedUse: "Urban Primary Health Center & Senior Citizen Activity Daycare",
  },
  {
    id: "fac-hyd-02",
    name: "Secunderabad Station Outer Public Toilet Complex",
    type: "toilet",
    district: "Hyderabad",
    state: "Telangana",
    lat: 17.4399,
    lng: 78.5017,
    officialStatus: "DEFUNCT",
    abandonmentScore: 82,
    populationCatchment: 26000,
    establishedYear: 2018,
    lastInspection: "6 months ago",
    conditionNotes: "Continuous foul odor due to broken exhaust and dead pipeline. Padlock placed on women's wing causing extreme commuter hardship.",
    citizenReportCount: 13,
    recommendedAction: "REPAIR",
    proposedUse: "Deep Sanitize, Exhaust Installation, Dual Water Supply Line Restoration",
  },
  {
    id: "fac-hyd-03",
    name: "Mission Bhagiratha Water Dispenser (Charminar South)",
    type: "water",
    district: "Hyderabad",
    state: "Telangana",
    lat: 17.3598,
    lng: 78.4744,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 12,
    populationCatchment: 31000,
    establishedYear: 2021,
    lastInspection: "9 days ago",
    conditionNotes: "High-quality RO distribution terminal functioning reliably across dense heritage bazaar area.",
    citizenReportCount: 2,
    recommendedAction: "MAINTAIN",
  },

  // ─── 6. UTTAR PRADESH (VARANASI & KANPUR) ───────────────────────────────────
  {
    id: "fac-up-01",
    name: "Basic Shiksha Parishad Primary School (Adampur)",
    type: "school",
    district: "Varanasi",
    state: "Uttar Pradesh",
    lat: 25.3289,
    lng: 83.0211,
    officialStatus: "ABANDONED",
    abandonmentScore: 93,
    populationCatchment: 16000,
    establishedYear: 1993,
    lastInspection: "19 months ago",
    conditionNotes: "Enrollment dwindled to zero 4 years ago. Solid stone building in weavers pocket lying dark and unmaintained.",
    citizenReportCount: 10,
    recommendedAction: "REPURPOSE",
    proposedUse: "Handloom Weavers Skill & Common Facility Center",
  },
  {
    id: "fac-up-02",
    name: "Nagar Nigam Smart Toilet (Ghat Corridor)",
    type: "toilet",
    district: "Varanasi",
    state: "Uttar Pradesh",
    lat: 25.3076,
    lng: 83.0107,
    officialStatus: "DEFUNCT",
    abandonmentScore: 83,
    populationCatchment: 35000,
    establishedYear: 2019,
    lastInspection: "4 months ago",
    conditionNotes: "Pilgrim density corridor. Sludge evacuation line choked; iron shutter down with handwritten note 'No Water'.",
    citizenReportCount: 17,
    recommendedAction: "REPAIR",
    proposedUse: "Sewer Line Desilting, Dedicated Water Tanker Link, UPI Pay-System",
  },
  {
    id: "fac-up-03",
    name: "Jal Nigam RO Water Station (Kanpur Central)",
    type: "water",
    district: "Varanasi",
    state: "Uttar Pradesh",
    lat: 26.4499,
    lng: 80.3319,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 14,
    populationCatchment: 24000,
    establishedYear: 2020,
    lastInspection: "14 days ago",
    conditionNotes: "Treated clean drinking water dispensing facility operating at full 10,000 LPD design capacity.",
    citizenReportCount: 1,
    recommendedAction: "MAINTAIN",
  },

  // ─── 7. WEST BENGAL (KOLKATA) ───────────────────────────────────────────────
  {
    id: "fac-wb-01",
    name: "KMC Primary School Building (Topsia Canal Road)",
    type: "school",
    district: "Kolkata",
    state: "West Bengal",
    lat: 22.5398,
    lng: 88.3842,
    officialStatus: "ABANDONED",
    abandonmentScore: 89,
    populationCatchment: 27000,
    establishedYear: 1987,
    lastInspection: "13 months ago",
    conditionNotes: "Building shut following merger. Structurally stable masonry building with 8 empty rooms right amidst high-density leather worker colony.",
    citizenReportCount: 7,
    recommendedAction: "REPURPOSE",
    proposedUse: "Urban Health Post & Maternal Immunization Hub",
  },
  {
    id: "fac-wb-02",
    name: "Howrah Station Foreshore Sanitation Unit",
    type: "toilet",
    district: "Kolkata",
    state: "West Bengal",
    lat: 22.5851,
    lng: 88.3426,
    officialStatus: "DEFUNCT",
    abandonmentScore: 88,
    populationCatchment: 42000,
    establishedYear: 2016,
    lastInspection: "7 months ago",
    conditionNotes: "Major commuter transfer zone. Water connection severed during road widening; facility padlocked for over half a year.",
    citizenReportCount: 22,
    recommendedAction: "REPAIR",
    proposedUse: "Re-pipe Water Inflow, Tile Overhaul & 24/7 Attendant Posting",
  },
  {
    id: "fac-wb-03",
    name: "KMC Park Circus Drinking Water ATM",
    type: "water",
    district: "Kolkata",
    state: "West Bengal",
    lat: 22.5448,
    lng: 88.3697,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 11,
    populationCatchment: 29000,
    establishedYear: 2021,
    lastInspection: "8 days ago",
    conditionNotes: "Consistent purified water supply serving local market traders and transit pedestrians.",
    citizenReportCount: 0,
    recommendedAction: "MAINTAIN",
  },

  // ─── 8. GUJARAT (AHMEDABAD & SURAT) ─────────────────────────────────────────
  {
    id: "fac-guj-01",
    name: "AMC Municipal Primary School (Asarwa Mill Zone)",
    type: "school",
    district: "Ahmedabad",
    state: "Gujarat",
    lat: 23.0456,
    lng: 72.6078,
    officialStatus: "ABANDONED",
    abandonmentScore: 85,
    populationCatchment: 18000,
    establishedYear: 1994,
    lastInspection: "12 months ago",
    conditionNotes: "Vacant 2-story brick building with closed mill colonies nearby. Spacious yard suitable for neighborhood vocational training.",
    citizenReportCount: 5,
    recommendedAction: "REPURPOSE",
    proposedUse: "Industrial Skill Training & Women Sewing Cooperative Center",
  },
  {
    id: "fac-guj-02",
    name: "Vatva GIDC Industrial Labor Restroom Block",
    type: "toilet",
    district: "Ahmedabad",
    state: "Gujarat",
    lat: 22.9587,
    lng: 72.6289,
    officialStatus: "DEFUNCT",
    abandonmentScore: 81,
    populationCatchment: 22000,
    establishedYear: 2017,
    lastInspection: "5 months ago",
    conditionNotes: "Burnt pump motor, blocked vents, door hinges broken. Industrial migrant laborers deprived of basic sanitation.",
    citizenReportCount: 9,
    recommendedAction: "REPAIR",
    proposedUse: "Submersible Motor Replacement, New Vents & Solar Lighting",
  },
  {
    id: "fac-guj-03",
    name: "Tapi RO Water Dispensing Hub (Surat)",
    type: "water",
    district: "Ahmedabad",
    state: "Gujarat",
    lat: 21.1702,
    lng: 72.8311,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 9,
    populationCatchment: 33000,
    establishedYear: 2022,
    lastInspection: "4 days ago",
    conditionNotes: "Top-tier operational record dispensing 20,000 liters of chilled pure water per day.",
    citizenReportCount: 1,
    recommendedAction: "MAINTAIN",
  },

  // ─── 9. RAJASTHAN (JAIPUR & JODHPUR) ────────────────────────────────────────
  {
    id: "fac-raj-01",
    name: "Govt Secondary School Annex (Sanganer Outer)",
    type: "school",
    district: "Jaipur",
    state: "Rajasthan",
    lat: 26.8154,
    lng: 75.7689,
    officialStatus: "UNDERUTILIZED",
    abandonmentScore: 70,
    populationCatchment: 15000,
    establishedYear: 2002,
    lastInspection: "6 months ago",
    conditionNotes: "Half the school block is locked with cobwebs and wild grass while nearby peri-urban students lack computer access.",
    citizenReportCount: 4,
    recommendedAction: "REPURPOSE",
    proposedUse: "Village Digital Knowledge & e-Mitra Citizen Services Hub",
  },
  {
    id: "fac-raj-02",
    name: "Jodhpur Walled City Public Toilet",
    type: "toilet",
    district: "Jaipur",
    state: "Rajasthan",
    lat: 26.2918,
    lng: 73.0169,
    officialStatus: "DEFUNCT",
    abandonmentScore: 84,
    populationCatchment: 19000,
    establishedYear: 2018,
    lastInspection: "8 months ago",
    conditionNotes: "Severed municipal water pipeline in rocky terrain. Facility closed with chain; heritage tourists and local shopkeepers affected.",
    citizenReportCount: 12,
    recommendedAction: "REPAIR",
    proposedUse: "New HDPE Pipeline Route, Rooftop Tank & Dedicated Cleaning Protocol",
  },
  {
    id: "fac-raj-03",
    name: "PHED Solar Deep-Bore RO Station (Jaipur)",
    type: "water",
    district: "Jaipur",
    state: "Rajasthan",
    lat: 26.9602,
    lng: 75.8456,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 10,
    populationCatchment: 16000,
    establishedYear: 2021,
    lastInspection: "11 days ago",
    conditionNotes: "Solar-powered deep bore plant functioning smoothly even during peak summer grid outages.",
    citizenReportCount: 0,
    recommendedAction: "MAINTAIN",
  },

  // ─── 10. ANDHRA PRADESH (VIZAG, VIJAYAWADA, GUNTUR, TIRUPATI) ───────────────
  {
    id: "fac-vskp-01",
    name: "Zilla Parishad Primary School (Pendurthi)",
    type: "school",
    district: "Visakhapatnam",
    state: "Andhra Pradesh",
    lat: 17.8284,
    lng: 83.1985,
    officialStatus: "ABANDONED",
    abandonmentScore: 92,
    populationCatchment: 14200,
    establishedYear: 1994,
    lastInspection: "18 months ago",
    conditionNotes: "Zero student enrollment for 3 years following cluster consolidation. Sturdy RCC building with 6 classrooms completely overgrown with wild vegetation.",
    citizenReportCount: 6,
    recommendedAction: "REPURPOSE",
    proposedUse: "Primary Health Clinic & Anganwadi Center",
  },
  {
    id: "fac-vskp-02",
    name: "Pendurthi Public Sanitation Block #4",
    type: "toilet",
    district: "Visakhapatnam",
    state: "Andhra Pradesh",
    lat: 17.8251,
    lng: 83.2041,
    officialStatus: "DEFUNCT",
    abandonmentScore: 84,
    populationCatchment: 6500,
    establishedYear: 2018,
    lastInspection: "7 months ago",
    conditionNotes: "Padlocked steel gate, dry overhead tank, broken external tap. Citizen reports indicate maintenance halted due to municipal contractor disputes.",
    citizenReportCount: 9,
    recommendedAction: "REPAIR",
    proposedUse: "Restore Water Line, Unlock Doors & Transfer to Women SHG Caretaker",
  },
  {
    id: "fac-vskp-03",
    name: "MVP Colony RO Drinking Water Plant",
    type: "water",
    district: "Visakhapatnam",
    state: "Andhra Pradesh",
    lat: 17.7428,
    lng: 83.3371,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 12,
    populationCatchment: 12000,
    establishedYear: 2020,
    lastInspection: "15 days ago",
    conditionNotes: "Functional 2000 LPH RO water plant dispensing clean water to 800+ households daily.",
    citizenReportCount: 1,
    recommendedAction: "MAINTAIN",
  },
  {
    id: "fac-vja-01",
    name: "Municipal Primary School (Sector 3, Vijayawada)",
    type: "school",
    district: "Vijayawada",
    state: "Andhra Pradesh",
    lat: 16.5186,
    lng: 80.6421,
    officialStatus: "UNDERUTILIZED",
    abandonmentScore: 78,
    populationCatchment: 19500,
    establishedYear: 1988,
    lastInspection: "8 months ago",
    conditionNotes: "Only 28 students enrolled across 8 classrooms. High school built nearby absorbed student body; 6 large classrooms locked and deteriorating.",
    citizenReportCount: 4,
    recommendedAction: "REPURPOSE",
    proposedUse: "Community Digital Library & Vocational IT Training Center",
  },
  {
    id: "fac-vja-02",
    name: "Autonagar Industrial Workers Public Toilet",
    type: "toilet",
    district: "Vijayawada",
    state: "Andhra Pradesh",
    lat: 16.4952,
    lng: 80.6894,
    officialStatus: "ABANDONED",
    abandonmentScore: 91,
    populationCatchment: 11000,
    establishedYear: 2015,
    lastInspection: "14 months ago",
    conditionNotes: "Fully abandoned facility with broken roof panels, cracked septic tank, and dry plumbing. 4000+ daily mechanics and workers lack sanitation.",
    citizenReportCount: 14,
    recommendedAction: "REPAIR",
    proposedUse: "Structural Roof Rebuild, Septic Tank Overhaul & Modernization",
  },
  {
    id: "fac-gnt-01",
    name: "Old Market Yard RO Water ATM (Guntur)",
    type: "water",
    district: "Guntur",
    state: "Andhra Pradesh",
    lat: 16.3067,
    lng: 80.4365,
    officialStatus: "DEFUNCT",
    abandonmentScore: 88,
    populationCatchment: 13500,
    establishedYear: 2017,
    lastInspection: "9 months ago",
    conditionNotes: "Burned out electric transformer and non-functional RO filtration membranes. Hundreds of vegetable vendors currently buy unhygienic water tankers.",
    citizenReportCount: 11,
    recommendedAction: "REPAIR",
    proposedUse: "New Motor Transformer, Membrane Replacement & Smart Metering",
  },
  {
    id: "fac-tir-01",
    name: "Renigunta Peri-urban Primary Health Sub-Center",
    type: "health",
    district: "Tirupati",
    state: "Andhra Pradesh",
    lat: 13.6392,
    lng: 79.5184,
    officialStatus: "OPERATIONAL",
    abandonmentScore: 16,
    populationCatchment: 17000,
    establishedYear: 2019,
    lastInspection: "20 days ago",
    conditionNotes: "Active maternal immunization post with regular doctor visits, clean wards, and medicine inventory.",
    citizenReportCount: 1,
    recommendedAction: "MAINTAIN",
  },
];

export const seedCivicReports = [
  {
    id: "civ-del-01",
    facilityId: "fac-del-02",
    facilityName: "DDA Community Sanitation Complex (Rohini Sector 22)",
    district: "Central Delhi",
    lat: 28.7182,
    lng: 77.0673,
    issueType: "LOCKED_TOILET",
    issueTitle: "Locked with heavy iron chains for 8 months",
    description: "The main door has been chained and padlocked since winter. No caretaker or water supply. Women and children in the slum pocket are forced to walk half a kilometer to open railway tracks.",
    reportedBy: "Sanjay Kumar",
    submittedAt: "2026-09-28T08:30:00Z",
    aiConfidence: 94,
    status: "CONFIRMED_ISSUE",
  },
  {
    id: "civ-mum-01",
    facilityId: "fac-mum-02",
    facilityName: "Mankhurd Transit Camp Sanitation Block #12",
    district: "Mumbai Suburban",
    lat: 19.0522,
    lng: 72.9328,
    issueType: "DEFUNCT_FACILITY",
    issueTitle: "Sewage overflow and blocked drains",
    description: "Stagnant drainage water has flooded the entryway. All 10 cubicles are jammed with waste and zero water flows through the taps. Severe disease risk in transit colony.",
    reportedBy: "Farida Sheikh",
    submittedAt: "2026-10-01T11:15:00Z",
    aiConfidence: 96,
    status: "CONFIRMED_ISSUE",
  },
  {
    id: "civ-blr-01",
    facilityId: "fac-blr-02",
    facilityName: "Shivajinagar Bus Terminal Public E-Toilet",
    district: "Bengaluru Urban",
    lat: 12.9857,
    lng: 77.6057,
    issueType: "LOCKED_TOILET",
    issueTitle: "Smart sensors broken and entrance barricaded",
    description: "Coin/card sensor display has been flashing error for months. Doors remain stuck in lock state and no BMTC technician has visited.",
    reportedBy: "Ramesh Gowda",
    submittedAt: "2026-10-02T14:45:00Z",
    aiConfidence: 91,
    status: "CONFIRMED_ISSUE",
  },
  {
    id: "civ-up-01",
    facilityId: "fac-up-02",
    facilityName: "Nagar Nigam Smart Toilet (Ghat Corridor)",
    district: "Varanasi",
    lat: 25.3076,
    lng: 83.0107,
    issueType: "DEFUNCT_FACILITY",
    issueTitle: "Water supply cutoff along pilgrim ghat",
    description: "Pilgrims from across India arrive here only to find dry pipes and locked cubicles. Hand-painted 'Out of Order' sign has stayed for 4 months.",
    reportedBy: "Pandit Ramadhar",
    submittedAt: "2026-10-03T09:20:00Z",
    aiConfidence: 95,
    status: "CONFIRMED_ISSUE",
  },
  {
    id: "civ-wb-01",
    facilityId: "fac-wb-02",
    facilityName: "Howrah Station Foreshore Sanitation Unit",
    district: "Kolkata",
    lat: 22.5851,
    lng: 88.3426,
    issueType: "LOCKED_TOILET",
    issueTitle: "Foreshore toilet closed during peak rush hours",
    description: "Subway extension work cut off the main sewer connection and the municipality simply bolted the facility. Massive hardship for suburban commuters.",
    reportedBy: "Sourav Banerjee",
    submittedAt: "2026-10-03T16:10:00Z",
    aiConfidence: 93,
    status: "CONFIRMED_ISSUE",
  },
  {
    id: "civ-ap-01",
    facilityId: "fac-vskp-01",
    facilityName: "Zilla Parishad Primary School (Pendurthi)",
    district: "Visakhapatnam",
    lat: 17.8284,
    lng: 83.1985,
    issueType: "ABANDONED_SCHOOL",
    issueTitle: "Overgrown bushes and vacant school rooms",
    description: "Children go to the new school 2km away. This huge building is completely empty and becoming a haven for anti-social elements. Needs immediate community conversion.",
    reportedBy: "M. Appa Rao",
    submittedAt: "2026-10-04T10:05:00Z",
    aiConfidence: 92,
    status: "CONFIRMED_ISSUE",
  },
];

export const seedRecommendations = [
  {
    id: "rec-rep-01",
    type: "REPURPOSE",
    urgency: "CRITICAL",
    priorityScore: 96,
    targetFacilityId: "fac-del-01",
    targetFacilityName: "MCD Primary Model School (Narela)",
    district: "Central Delhi",
    affectedPopulation: 24000,
    estimatedCost: "₹18.5 Lakhs",
    timelineDays: 45,
    roiScore: 9.7,
    rationale: "Sturdy 2-story building with 10 vacant classrooms in a high-growth perimeter. Repurposing avoids ₹95L new construction costs and provides immediate maternal health and creche services to industrial families.",
    proposedUse: "Maternal Health Clinic & Anganwadi Creche Hub",
    actionItems: [
      "Municipal council resolution approving functional reassignment from Education to Health",
      "Interior partition overhaul, sanitation fixtures and solar electrical wiring",
      "Staffing with 2 medical officers, 4 nurses and creche attendants under National Health Mission",
    ],
    status: "APPROVED_FOR_TENDER",
  },
  {
    id: "rec-rep-02",
    type: "REPURPOSE",
    urgency: "HIGH",
    priorityScore: 94,
    targetFacilityId: "fac-mum-01",
    targetFacilityName: "BMC Municipal Primary School (Kurla West)",
    district: "Mumbai Suburban",
    affectedPopulation: 36000,
    estimatedCost: "₹24.0 Lakhs",
    timelineDays: 60,
    roiScore: 9.5,
    rationale: "Closed 3-floor civic property located between Dharavi and Kurla. Repurposing into an IT coding and vocational skill incubator unlocks high earning potential for local slum youth.",
    proposedUse: "Youth Digital Skill & Innovation Hub",
    actionItems: [
      "Cabinet sign-off for inter-departmental infrastructure transfer",
      "Furnishing 6 classrooms with 120 desktop terminals, fiber internet, and UPS backups",
      "Partnership with NSDC vocational training partners for certified trade curricula",
    ],
    status: "PROPOSAL_READY",
  },
  {
    id: "rec-rep-03",
    type: "REPURPOSE",
    urgency: "HIGH",
    priorityScore: 91,
    targetFacilityId: "fac-blr-01",
    targetFacilityName: "BBMP Primary School (Peenya 2nd Stage)",
    district: "Bengaluru Urban",
    affectedPopulation: 21000,
    estimatedCost: "₹14.2 Lakhs",
    timelineDays: 40,
    roiScore: 9.2,
    rationale: "Prime Peenya industrial hub structure currently vulnerable to illegal scrap encroachment. High demand from women garment workers for child daycare and self-help group stitching cooperatives.",
    proposedUse: "Garment Workers Creche & Women SHG Cooperative Hub",
    actionItems: [
      "Evict boundary encroachment and construct security perimeter",
      "Child-safe interior revamp with soft flooring, play equipment, and feeding room",
      "Handover facility administration to registered Women Industrial Self-Help Federation",
    ],
    status: "PROPOSAL_READY",
  },
  {
    id: "rec-fix-01",
    type: "REPAIR",
    urgency: "CRITICAL",
    priorityScore: 98,
    targetFacilityId: "fac-del-02",
    targetFacilityName: "DDA Community Sanitation Complex (Rohini Sector 22)",
    district: "Central Delhi",
    affectedPopulation: 11000,
    estimatedCost: "₹3.8 Lakhs",
    timelineDays: 14,
    roiScore: 9.9,
    rationale: "Low-cost mechanical fix solves acute community deprivation. Padlock and burned motor force 11,000 slum dwellers into open defecation across nearby railway buffers.",
    proposedUse: "Complete Submersible Motor Overhaul, Sensor Repair & Unlocking",
    actionItems: [
      "Emergency municipal repair sanction under Swachh Bharat Urban allocation",
      "Install heavy-duty 5 HP commercial submersible pump and automatic water level sensor",
      "Assign registered local Mahila Arogya Samiti for daily cleanliness monitoring",
    ],
    status: "APPROVED_BY_OFFICER",
  },
  {
    id: "rec-fix-02",
    type: "REPAIR",
    urgency: "CRITICAL",
    priorityScore: 97,
    targetFacilityId: "fac-mum-02",
    targetFacilityName: "Mankhurd Transit Camp Sanitation Block #12",
    district: "Mumbai Suburban",
    affectedPopulation: 18500,
    estimatedCost: "₹5.5 Lakhs",
    timelineDays: 20,
    roiScore: 9.8,
    rationale: "Severe cholera and dengue hazard. Collapsed drainage line has turned public facility into an open sewage pond, impacting 3500 transit families.",
    proposedUse: "Sewer Line Excavation, Bio-Digester Tank & Solar Power Link",
    actionItems: [
      "Deploy municipal suction excavators to clear underground trunk line",
      "Replace cracked concrete pipelines with chemical-resistant HDPE lines",
      "Install solar rooftop panels ensuring uninhibited 24/7 night lighting",
    ],
    status: "APPROVED_FOR_TENDER",
  },
  {
    id: "rec-fix-03",
    type: "REPAIR",
    urgency: "HIGH",
    priorityScore: 93,
    targetFacilityId: "fac-up-02",
    targetFacilityName: "Nagar Nigam Smart Toilet (Ghat Corridor)",
    district: "Varanasi",
    affectedPopulation: 35000,
    estimatedCost: "₹4.2 Lakhs",
    timelineDays: 15,
    roiScore: 9.4,
    rationale: "Prime cultural corridor serving millions of pilgrims annually. Facility shutdown damages city hygiene and public riverfront integrity.",
    proposedUse: "Deep Desilting, Dedicated Water Line Connection & Automated UPI Entry",
    actionItems: [
      "Desilt riverfront drainage chamber using high-pressure jetting machines",
      "Install 10,000-liter buffer water storage tank linked to municipal main",
      "Introduce contactless entry turnstiles preventing vandalism",
    ],
    status: "PROPOSAL_READY",
  },
  {
    id: "rec-dev-01",
    type: "NEWLY_DEVELOP",
    urgency: "CRITICAL",
    priorityScore: 95,
    targetFacilityId: null,
    targetFacilityName: "Dharavi Sector 5 Eco-Sanitation Hub",
    district: "Mumbai Suburban",
    affectedPopulation: 28000,
    estimatedCost: "₹38.0 Lakhs",
    timelineDays: 90,
    roiScore: 9.6,
    rationale: "Demographic satellite scan reveals 28,000 residents living beyond 800m of any operational sanitation infrastructure in dense transit cluster.",
    proposedUse: "New Construction: 24-Seat Multi-Story Eco-Sanitation & Bathing Complex",
    actionItems: [
      "Clear identified 450 sq. meter municipal open pocket with Slum Rehabilitation Authority",
      "Construct 2-story modular prefabricated structure with rainwater harvesting and solar hot water",
      "Integrate automated greywater recycling for flushing",
    ],
    status: "PROPOSAL_READY",
  },
  {
    id: "rec-dev-02",
    type: "NEWLY_DEVELOP",
    urgency: "HIGH",
    priorityScore: 92,
    targetFacilityId: null,
    targetFacilityName: "Varanasi Adampur Slum Cluster Drinking Water ATM",
    district: "Varanasi",
    affectedPopulation: 14000,
    estimatedCost: "₹14.5 Lakhs",
    timelineDays: 45,
    roiScore: 9.3,
    rationale: "Dense handloom weaver settlement where groundwater contains heavy minerals and zero piped treated drinking water reaches interior alleyways.",
    proposedUse: "New Construction: 5000 LPH Solar RO Purified Water Dispensing Center",
    actionItems: [
      "Drill deep aquifer tube well with hydro-geological clearance",
      "Install multi-stage RO filtration with remineralization unit",
      "Dispense clean water at subsidized ₹5 per 20L can using RFID smart cards",
    ],
    status: "PLANNED",
  },
  {
    id: "rec-dev-03",
    type: "NEWLY_DEVELOP",
    urgency: "HIGH",
    priorityScore: 90,
    targetFacilityId: null,
    targetFacilityName: "Bengaluru Peenya Outer Primary Health Sub-Center",
    district: "Bengaluru Urban",
    affectedPopulation: 31000,
    estimatedCost: "₹52.0 Lakhs",
    timelineDays: 120,
    roiScore: 9.1,
    rationale: "Fast expanding migrant manufacturing cluster lacking public healthcare within 7km. Urgent maternal and trauma facility needed.",
    proposedUse: "New Construction: 24/7 Urban Primary Health Center (UPHC)",
    actionItems: [
      "Sanction DPR under National Urban Health Mission (NUHM)",
      "Construct 6-bed emergency observation and maternal delivery unit",
      "Staff with 3 medical officers, lab technician, and 24x7 ambulance link",
    ],
    status: "PROPOSAL_READY",
  },
];

export const seedResolutionPairs = [
  {
    id: "res-del-01",
    facilityName: "Rohini Sector 22 Community Restroom Cluster",
    district: "Central Delhi",
    issueReported: "Rusted padlock removed, fresh pipeline installed, and 24/7 attendant deployed",
    reportedDate: "2026-08-15",
    resolvedDate: "2026-09-20",
    reportedBy: "Sanjay Kumar",
    resolvedBy: "Assistant Engineer Alok Sharma (DDA)",
    aiVerificationScore: 96,
    status: "VERIFIED_RESOLVED",
    aiInspectionReport: "AI visual inspection verifies padlock eliminated, new stainless steel fixtures installed, and running water confirmed across all 12 cubicles.",
  },
  {
    id: "res-mum-01",
    facilityName: "Kurla West Municipal School Ground Floor Renovation",
    district: "Mumbai Suburban",
    issueReported: "Wild vegetation cleared, classrooms converted into digital learning lab",
    reportedDate: "2026-07-20",
    resolvedDate: "2026-09-18",
    reportedBy: "Farida Sheikh",
    resolvedBy: "Ward Officer Pravin Kadam (BMC)",
    aiVerificationScore: 94,
    status: "VERIFIED_RESOLVED",
    aiInspectionReport: "Interior classrooms repainted, 30 computer terminals active, and security gates reinforced for community youth access.",
  },
  {
    id: "res-blr-01",
    facilityName: "Shivajinagar E-Toilet Hydraulic Sensor Repair",
    district: "Bengaluru Urban",
    issueReported: "Sensors calibrated, water motor replaced, automated entry functional",
    reportedDate: "2026-08-10",
    resolvedDate: "2026-09-24",
    reportedBy: "Ramesh Gowda",
    resolvedBy: "Junior Engineer C. Narayan (BBMP)",
    aiVerificationScore: 97,
    status: "VERIFIED_RESOLVED",
    aiInspectionReport: "Power and water telemetry normal. Smart coin/UPI validation verified with zero mechanical obstructions.",
  },
  {
    id: "res-vskp-01",
    facilityName: "Tirupati Renigunta Sanitation Block #2",
    district: "Tirupati",
    issueReported: "Padlocked steel gate and broken water pipe restored",
    reportedDate: "2026-08-10",
    resolvedDate: "2026-09-12",
    reportedBy: "S. Murthy",
    resolvedBy: "Assistant Engineer V. Prasad",
    aiVerificationScore: 95,
    status: "VERIFIED_RESOLVED",
    aiInspectionReport: "AI visual inspection confirms padlock has been removed, fresh paint applied, water pipe connected, and entrance is unobstructed for public use.",
  },
  {
    id: "res-vja-01",
    facilityName: "Vijayawada Sector 3 Water Tap Leakage",
    district: "Vijayawada",
    issueReported: "Severed control valve causing continuous potable water wastage",
    reportedDate: "2026-09-01",
    resolvedDate: "2026-09-15",
    reportedBy: "N. Bhavani",
    resolvedBy: "Water Works Inspector R. Raju",
    aiVerificationScore: 98,
    status: "VERIFIED_RESOLVED",
    aiInspectionReport: "Zero moisture leakage detected around joint. High-grade brass shutoff installed with tamper-proof seal.",
  },
];
